---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - api.core.shon.io
  resources:
  - kafkaadaptors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - api.core.shon.io
  resources:
  - kafkaadaptors/finalizers
  verbs:
  - update
- apiGroups:
  - api.core.shon.io
  resources:
  - kafkaadaptors/status
  verbs:
  - get
  - patch
  - update
