//go:build !ignore_autogenerated

/*
Copyright 2025 ShonPhand.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KafkaAdaptors) DeepCopyInto(out *KafkaAdaptors) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KafkaAdaptors.
func (in *KafkaAdaptors) DeepCopy() *KafkaAdaptors {
	if in == nil {
		return nil
	}
	out := new(KafkaAdaptors)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KafkaAdaptors) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KafkaAdaptorsList) DeepCopyInto(out *KafkaAdaptorsList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KafkaAdaptors, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KafkaAdaptorsList.
func (in *KafkaAdaptorsList) DeepCopy() *KafkaAdaptorsList {
	if in == nil {
		return nil
	}
	out := new(KafkaAdaptorsList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KafkaAdaptorsList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KafkaAdaptorsSpec) DeepCopyInto(out *KafkaAdaptorsSpec) {
	*out = *in
	in.KafkaConnection.DeepCopyInto(&out.KafkaConnection)
	if in.Transformations != nil {
		in, out := &in.Transformations, &out.Transformations
		*out = make([]Transformation, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KafkaAdaptorsSpec.
func (in *KafkaAdaptorsSpec) DeepCopy() *KafkaAdaptorsSpec {
	if in == nil {
		return nil
	}
	out := new(KafkaAdaptorsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KafkaAdaptorsStatus) DeepCopyInto(out *KafkaAdaptorsStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KafkaAdaptorsStatus.
func (in *KafkaAdaptorsStatus) DeepCopy() *KafkaAdaptorsStatus {
	if in == nil {
		return nil
	}
	out := new(KafkaAdaptorsStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KafkaConnection) DeepCopyInto(out *KafkaConnection) {
	*out = *in
	if in.BootstrapServer != nil {
		in, out := &in.BootstrapServer, &out.BootstrapServer
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KafkaConnection.
func (in *KafkaConnection) DeepCopy() *KafkaConnection {
	if in == nil {
		return nil
	}
	out := new(KafkaConnection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Transformation) DeepCopyInto(out *Transformation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Transformation.
func (in *Transformation) DeepCopy() *Transformation {
	if in == nil {
		return nil
	}
	out := new(Transformation)
	in.DeepCopyInto(out)
	return out
}
